algoritmo "semnome"
// Função :
// Autor :
// Data : 07/03/2022
// Seção de Declarações 
var
nome:caracter
idade:inteiro
salario:real
inicio
// Seção de Comandos
escreval ("Digite seu nome: ")
leia(nome)
escreval("Ola ",nome," prazer em conhecer")
escreval ("Digite sua idade: ")
escreval ("Sua ",idade," Entendi")
leia (idade)
escreval ("Digite seu salario: ")
escreval ("Seu ",salario," Entendi")
leia(salario)
fimalgoritmo
